apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt2db-go.fullname" . }}-config
  labels: {{- include "mqtt2db-go.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
