{{- if and .Values.secret.create (not .Values.secret.existingName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt2db-go.fullname" . }}-secret
  labels: {{- include "mqtt2db-go.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
